"""Assemble the final ONBOARDING.md output."""

from __future__ import annotations

from pathlib import Path, PurePosixPath

from code_onboard.analysis.entry_points import EntryPoint
from code_onboard.analysis.hotspots import Hotspot
from code_onboard.parsing.models import FileSummary


def _module_map(summaries: list[FileSummary]) -> str:
    """Build a directory summary table."""
    dir_stats: dict[str, dict] = {}
    for s in summaries:
        d = str(PurePosixPath(s.relative_path).parent)
        if d == ".":
            d = "(root)"
        if d not in dir_stats:
            dir_stats[d] = {"files": 0, "functions": 0, "classes": 0, "lines": 0}
        dir_stats[d]["files"] += 1
        dir_stats[d]["functions"] += len(s.functions)
        dir_stats[d]["classes"] += len(s.classes)
        dir_stats[d]["lines"] += s.line_count

    lines = ["| Directory | Files | Functions | Classes | Lines |",
             "|-----------|-------|-----------|---------|-------|"]
    for d in sorted(dir_stats):
        st = dir_stats[d]
        lines.append(f"| `{d}` | {st['files']} | {st['functions']} | {st['classes']} | {st['lines']} |")

    return "\n".join(lines)


def assemble_onboarding(
    entries: list[EntryPoint],
    hotspots: list[Hotspot],
    reading_path: list[str],
    arch_diagram: str,
    hotspot_diagram: str,
    file_summaries: list[FileSummary],
    repo_path: Path,
    narratives: dict[str, str] | None = None,
) -> str:
    narr = narratives or {}
    sections: list[str] = []

    # Title
    repo_name = repo_path.name
    sections.append(f"# {repo_name} - Onboarding Guide\n")
    sections.append("*Auto-generated by [code-onboard](https://github.com/code-onboard/code-onboard)*\n")

    # Section 1: How This App Starts
    sections.append("## 1. How This App Starts\n")
    if narr.get("entry_points"):
        sections.append(narr["entry_points"] + "\n")

    if entries:
        sections.append("| Entry Point | Kind | Description |")
        sections.append("|-------------|------|-------------|")
        for ep in entries:
            sections.append(f"| `{ep.path}` | {ep.kind} | {ep.description} |")
        sections.append("")
    else:
        sections.append("No clear entry points detected.\n")

    # Section 2: Architecture Overview
    sections.append("## 2. Architecture Overview\n")
    if narr.get("architecture"):
        sections.append(narr["architecture"] + "\n")

    if arch_diagram:
        sections.append("```mermaid")
        sections.append(arch_diagram)
        sections.append("```\n")

    # Section 3: Top Hotspots
    sections.append(f"## 3. Top {len(hotspots)} Hotspots\n")
    if narr.get("hotspots"):
        sections.append(narr["hotspots"] + "\n")

    sections.append("These files are imported and called most frequently — understand them first.\n")
    if hotspots:
        sections.append("| # | File | Score | In-Degree | Calls | Key Symbols |")
        sections.append("|---|------|-------|-----------|-------|-------------|")
        for i, h in enumerate(hotspots, 1):
            symbols = ", ".join(h.classes[:3] + h.functions[:3])
            sections.append(f"| {i} | `{h.path}` | {h.score:.0f} | {h.in_degree} | {h.call_count} | {symbols} |")
        sections.append("")

    if hotspot_diagram:
        sections.append("```mermaid")
        sections.append(hotspot_diagram)
        sections.append("```\n")

    # Section 4: Suggested Reading Order
    sections.append("## 4. Suggested Reading Order\n")
    if narr.get("reading_order"):
        sections.append(narr["reading_order"] + "\n")

    if reading_path:
        for i, path in enumerate(reading_path, 1):
            sections.append(f"{i}. `{path}`")
        sections.append("")

    # Section 5: Module Responsibilities (LLM only)
    if narr.get("module_responsibilities"):
        sections.append("## 5. Module Responsibilities\n")
        sections.append(narr["module_responsibilities"])
        sections.append("")

    return "\n".join(sections)
